---
name: Deploy Azure TRE Multi Stage
# This workflow is the integration build run for pushes to the main branch
# It also runs on a schedule, serving as the nightly build

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: dev
        required: true

# This will prevent multiple runs of this entire workflow.
# We should NOT cancel in progress runs as that can destabilize the environment.
concurrency: "${{ github.workflow }}-${{ github.ref }}"

# TODO: bootstrap a new ACR. Using a manual one for now. 

jobs:
  build-devcontainer:
    name: Build Devcontainer
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      id: tre_deployment_acr_login
      run: az acr login --name "${{ secrets.TRE_DEPLOYMENT_ACR_NAME }}"

    - name: Build new devcontainer
      env:
        DOCKER_BUILDKIT: 1
      run: |
        set -e

        USER_UID=$(id -u)
        USER_GID=$(id -g)
        TRE_DEPLOYMENT_ACR=${{ secrets.TRE_DEPLOYMENT_ACR_NAME }}.azurecr.io
        echo "TRE_DEPLOYMENT_ACR=$TRE_DEPLOYMENT_ACR" >> "$GITHUB_ENV"

        docker_cache=()
        docker_cache+=(--cache-from "$TRE_DEPLOYMENT_ACR/tredeploy:${{ github.run_id }}")
        docker_cache+=(--cache-from "$TRE_DEPLOYMENT_ACR/tredeploy:latest")

        docker build . "${docker_cache[@]}" \
          -t "tredeploy:${{ github.run_id }}" -f ".devcontainer/Dockerfile" \
          --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg USER_UID="${USER_UID}" --build-arg USER_GID="${USER_GID}"

        docker image tag tredeploy:${{ github.run_id }} \
          $TRE_DEPLOYMENT_ACR/tredeploy:${{ github.run_id }}

        docker image push $TRE_DEPLOYMENT_ACR/tredeploy:${{ github.run_id }}

  build_core_images:
    # used to build images used by core infrastructure
    name: Build Core Docker Images
    runs-on: ubuntu-latest
    environment: dev
    needs: [build-devcontainer]
    strategy:
      fail-fast: true
      matrix:
        target: [build-and-push-api, build-and-push-resource-processor, build-and-push-airlock-processor]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Docker build
        uses: ./.github/actions/devcontainer_run_command
        with:
          COMMAND: "make ${{ matrix.target }}"
          DEVCONTAINER_TAG: ${{ github.run_id }}
          CI_CACHE_ACR_NAME: ${{ secrets.TRE_DEPLOYMENT_ACR_NAME }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ACR_NAME: ${{ secrets.TRE_DEPLOYMENT_ACR_NAME }}
  
  