---
name: Deploy Azure TRE Single Stage
# This workflow is called by the "Deploy Azure TRE Multi Stage" workflow, and will deploy a TRE to a given environment

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environmentName:
        description: The name of the Github Action's environment this will deploy into
        type: string
        required: true
    secrets:
      TRE_DEPLOYMENT_ACR:
        description: The ACR hostname containing the images to be brought into this environment
        required: true
      TRE_DEPLOYMENT_AZURE_CREDENTIALS:
        description: "Creds for the subscription which contains the deployment ACR"
        required: true

jobs:
  build-devcontainer:
    name: Pull Devcontainer
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2
    
    - name: Azure Login to Deployment environment
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TRE_DEPLOYMENT_AZURE_CREDENTIALS }}

    - name: ACR Login to Deployment ACR
      id: tre_deployment_acr_login
      run: az acr login --name "${{ inputs.TRE_DEPLOYMENT_ACR }}"

    - name: Pull Devcontainer
      env:
        DOCKER_BUILDKIT: 1
      run: |
        set -e
        docker image pull $TRE_DEPLOYMENT_ACR/tredev:${{ github.run_id }}
  
  